version: '3'

services:
  mailgen.ui:
    image: mailgen.ui:0.0.1
    build: .
    ports:
      - 3001:3000
    volumes:
      - '.:/fe-marketingtool'
      - '/fe-marketingtool/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production