const taxData = [
    {Id: 1, Country: "Australia", TaxCode: "au_abn", TaxIdText: "Australian Business Number (AU ABN)", Example: "12345678912"},
    {
        Id: 2,
        Country: "Australia",
        TaxCode: "au_arn",
        TaxIdText: "Australian Taxation Office Reference Number",
        Example: "123456789123"
    },
    {Id: 3, Country: "Austria", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "ATU12345678"},
    {Id: 4, Country: "Belgium", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "BE0123456789"},
    {Id: 5, Country: "Brazil", TaxCode: "br_cnpj", TaxIdText: "Brazilian CNPJ number", Example: "01.234.456/5432-10"},
    {Id: 6, Country: "Brazil", TaxCode: "br_cpf", TaxIdText: "Brazilian CPF number", Example: "123.456.789-87"},
    {Id: 7, Country: "Bulgaria", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "BG0123456789"},
    {Id: 8, Country: "Canada", TaxCode: "ca_bn", TaxIdText: "Canadian BN", Example: "123456789"},
    {Id: 9, Country: "Canada", TaxCode: "ca_gst_hst", TaxIdText: "Canadian GST/HST number", Example: "123456789RT0002"},
    {Id: 10, Country: "Canada", TaxCode: "ca_pst_bc", TaxIdText: "Canadian PST number", Example: "PST-1234-5678"},
    {Id: 11, Country: "Canada", TaxCode: "ca_pst_mb", TaxIdText: "Canadian PST number", Example: "123456-7"},
    {Id: 12, Country: "Canada", TaxCode: "ca_pst_sk", TaxIdText: "Canadian PST number", Example: "1234567"},
    {Id: 13, Country: "Canada", TaxCode: "ca_qst", TaxIdText: "Canadian QST number", Example: "1234567890TQ1234"},
    {Id: 14, Country: "Chile", TaxCode: "cl_tin", TaxIdText: "Chilean TIN", Example: "12.345.678-K"},
    {Id: 15, Country: "Croatia", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "HR12345678912"},
    {Id: 16, Country: "Cyprus", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "CY12345678Z"},
    {Id: 17, Country: "Czech Republic", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "CZ1234567890"},
    {Id: 18, Country: "Denmark", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "DK12345678"},
    {Id: 19, Country: "Estonia", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "EE123456789"},
    {Id: 20, Country: "Finland", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "FI12345678"},
    {Id: 21, Country: "France", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "FRAB123456789"},
    {Id: 22, Country: "Georgia", TaxCode: "ge_vat", TaxIdText: "Georgian VAT", Example: "123456789"},
    {Id: 23, Country: "Germany", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "DE123456789"},
    {Id: 24, Country: "Greece", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "EL123456789"},
    {Id: 25, Country: "Hong Kong", TaxCode: "hk_br", TaxIdText: "Hong Kong BR number", Example: "12345678"},
    {Id: 26, Country: "Hungary", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "HU12345678912"},
    {Id: 27, Country: "India", TaxCode: "in_gst", TaxIdText: "Indian GST number", Example: "12ABCDE3456FGZH"},
    {Id: 28, Country: "Indonesia", TaxCode: "id_npwp", TaxIdText: "Indonesian NPWP number", Example: "12.345.678.9-012.345"},
    {Id: 29, Country: "Ireland", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "IE1234567AB"},
    {Id: 30, Country: "Israel", TaxCode: "il_vat", TaxIdText: "Israel VAT", Example: "000012345"},
    {Id: 31, Country: "Italy", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "IT12345678912"},
    {Id: 32, Country: "Japan", TaxCode: "jp_cn", TaxIdText: "Japanese Corporate Number", Example: "1234567891234"},
    {
        Id: 33,
        Country: "Japan",
        TaxCode: "jp_rn",
        TaxIdText: "Japanese Registered Foreign Businesses' Registration Number",
        Example: "12345"
    },
    {Id: 34, Country: "Korea, Republic of", TaxCode: "kr_brn", TaxIdText: "Korean BRN", Example: "123-45-67890"},
    {Id: 35, Country: "Latvia", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "LV12345678912"},
    {Id: 36, Country: "Liechtenstein", TaxCode: "li_uid", TaxIdText: "Liechtensteinian UID number", Example: "CHE123456789"},
    {Id: 37, Country: "Lithuania", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "LT123456789123"},
    {Id: 38, Country: "Luxembourg", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "LU12345678"},
    {Id: 39, Country: "Malaysia", TaxCode: "my_frp", TaxIdText: "Malaysian FRP number", Example: "12345678"},
    {Id: 40, Country: "Malaysia", TaxCode: "my_itn", TaxIdText: "Malaysian ITN	C", Example: "1234567890"},
    {Id: 41, Country: "Malaysia", TaxCode: "my_sst", TaxIdText: "Malaysian SST number", Example: "A12-3456-78912345"},
    {Id: 42, Country: "Malta", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "MT12345678"},
    {Id: 43, Country: "Mexico", TaxCode: "mx_rfc", TaxIdText: "Mexican RFC number", Example: "ABC010203AB9"},
    {Id: 44, Country: "Netherlands", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "NL123456789B12"},
    {Id: 45, Country: "New Zealand", TaxCode: "nz_gst", TaxIdText: "New Zealand GST number", Example: "123456789"},
    {Id: 46, Country: "Norway", TaxCode: "no_vat", TaxIdText: "Norwegian VAT number", Example: "123456789MVA"},
    {Id: 47, Country: "Poland", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "PL1234567890"},
    {Id: 48, Country: "Portugal", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "PT123456789"},
    {Id: 49, Country: "Romania", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "RO1234567891"},
    {Id: 50, Country: "Russian Federation", TaxCode: "ru_inn", TaxIdText: "Russian INN", Example: "1234567891"},
    {Id: 51, Country: "Russian Federation", TaxCode: "ru_kpp", TaxIdText: "Russian KPP", Example: "123456789"},
    {Id: 53, Country: "Saudi Arabia", TaxCode: "sa_vat", TaxIdText: "Saudi Arabia VAT", Example: "123456789012345"},
    {Id: 53, Country: "Singapore", TaxCode: "sg_gst", TaxIdText: "Singaporean GST", Example: "M12345678X"},
    {Id: 54, Country: "Singapore", TaxCode: "sg_uen", TaxIdText: "Singaporean UEN", Example: "123456789F"},
    {Id: 55, Country: "Slovakia", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "SK1234567891"},
    {Id: 56, Country: "Slovenia", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "SI12345678"},
    {Id: 57, Country: "South Africa", TaxCode: "za_vat", TaxIdText: "South African VAT number", Example: "4123456789"},
    {Id: 58, Country: "Spain", TaxCode: "es_cif", TaxIdText: "Spanish CIF number", Example: "A12345678"},
    {Id: 59, Country: "Spain", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "ESA1234567Z"},
    {Id: 60, Country: "Sweden", TaxCode: "eu_vat", TaxIdText: "European VAT number", Example: "SE123456789123"},
    {Id: 61, Country: "Switzerland", TaxCode: "ch_vat", TaxIdText: "Switzerland VAT number", Example: "CHE-123.456.789 MWST"},
    {Id: 62, Country: "Taiwan", TaxCode: "tw_vat", TaxIdText: "Taiwanese VAT", Example: "12345678"},
    {Id: 63, Country: "Thailand", TaxCode: "th_vat", TaxIdText: "Thai VAT", Example: "1234567891234"},
    {Id: 64, Country: "Ukraine", TaxCode: "ua_vat", TaxIdText: "Ukrainian VAT", Example: "123456789"},
    {Id: 65, Country: "United Arab Emirates",TaxCode: "ae_trn", TaxIdText: "United Arab Emirates TRN", Example: "123456789012345" },
    {Id: 66, Country: "United Kingdom", TaxCode: "gb_vat", TaxIdText: "United Kingdom VAT number", Example: "GB123456789"},
    {Id: 67, Country: "United Kingdom", TaxCode: "eu_vat", TaxIdText: "Northern Ireland VAT number", Example: "XI123456789"},
    {Id: 68, Country: "United States", TaxCode: "us_ein", TaxIdText: "United States EIN", Example: "12-3456789"}
]

const taxOptions = [
    {Index: 1, Text: "Australia", Id: "au_abn",},
    {Index: 2, Text: "Australia", Id: "au_arn",},
    {Index: 3,  Text: "Austria", Id: "eu_vat",},
    {Index: 4,  Text: "Belgium", Id: "eu_vat",},
    {Index: 5,  Text: "Brazil", Id: "br_cnpj",},
    {Index: 6,  Text: "Brazil", Id: "br_cpf",},
    {Index: 7,  Text: "Bulgaria", Id: "eu_vat",},
    {Index: 8,  Text: "Canada", Id: "ca_bn",},
    {Index: 9,  Text: "Canada", Id: "ca_gst_hst",},
    {Index: 10, Text: "Canada", Id: "ca_pst_bc",},
    {Index: 11, Text: "Canada", Id: "ca_pst_mb",},
    {Index: 12, Text: "Canada", Id: "ca_pst_sk",},
    {Index: 13, Text: "Canada", Id: "ca_qst",},
    {Index: 14, Text: "Chile", Id: "cl_tin",},
    {Index: 15, Text: "Croatia", Id: "eu_vat",},
    {Index: 16, Text: "Cyprus", Id: "eu_vat",},
    {Index: 17, Text: "Czech Republic", Id: "eu_vat",},
    {Index: 18, Text: "Denmark", Id: "eu_vat",},
    {Index: 19, Text: "Estonia", Id: "eu_vat",},
    {Index: 20, Text: "Finland", Id: "eu_vat",},
    {Index: 21, Text: "France", Id: "eu_vat",},
    {Index: 22, Text: "Georgia", Id: "ge_vat",},
    {Index: 23, Text: "Germany", Id: "eu_vat",},
    {Index: 24, Text: "Greece", Id: "eu_vat",},
    {Index: 25, Text: "Hong Kong", Id: "hk_br",},
    {Index: 26, Text: "Hungary", Id: "eu_vat",},
    {Index: 27, Text: "India", Id: "in_gst",},
    {Index: 28, Text: "Indonesia", Id: "id_npwp",},
    {Index: 29, Text: "Ireland", Id: "eu_vat",},
    {Index: 30, Text: "Israel", Id: "il_vat",},
    {Index: 31, Text: "Italy", Id: "eu_vat",},
    {Index: 32, Text: "Japan", Id: "jp_cn",},
    {Index: 33, Text: "Japan", Id: "jp_rn",},
    {Index: 34,Text: "Korea, Republic of", Id: "kr_brn",},
    {Index: 35,Text: "Latvia", Id: "eu_vat",},
    {Index: 36,Text: "Liechtenstein", Id: "li_uid",},
    {Index: 37,Text: "Lithuania", Id: "eu_vat",},
    {Index: 38,Text: "Luxembourg", Id: "eu_vat",},
    {Index: 39,Text: "Malaysia", Id: "my_frp",},
    {Index: 40,Text: "Malaysia", Id: "my_itn",},
    {Index: 41,Text: "Malaysia", Id: "my_sst",},
    {Index: 42,Text: "Malta", Id: "eu_vat",},
    {Index: 43,Text: "Mexico", Id: "mx_rfc",},
    {Index: 44,Text: "Netherlands", Id: "eu_vat",},
    {Index: 45,Text: "New Zealand", Id: "nz_gst",},
    {Index: 46,Text: "Norway", Id: "no_vat",},
    {Index: 47,Text: "Poland", Id: "eu_vat",},
    {Index: 48,Text: "Portugal", Id: "eu_vat",},
    {Index: 49,Text: "Romania", Id: "eu_vat",},
    {Index: 50,Text: "Russian Federation", Id: "ru_inn",},
    {Index: 51,Text: "Russian Federation", Id: "ru_kpp",},
    {Index: 53,Text: "Saudi Arabia", Id: "sa_vat",},
    {Index: 53,Text: "Singapore", Id: "sg_gst",},
    {Index: 54,Text: "Singapore", Id: "sg_uen",},
    {Index: 55,Text: "Slovakia", Id: "eu_vat",},
    {Index: 56,Text: "Slovenia", Id: "eu_vat",},
    {Index: 57,Text: "South Africa", Id: "za_vat",},
    {Index: 58,Text: "Spain", Id: "es_cif",},
    {Index: 59,Text: "Spain", Id: "eu_vat",},
    {Index: 60,Text: "Sweden", Id: "eu_vat",},
    {Index: 61,Text: "Switzerland", Id: "ch_vat",},
    {Index: 62,Text: "Taiwan", Id: "tw_vat",},
    {Index: 63,Text: "Thailand", Id: "th_vat",},
    {Index: 64,Text: "Ukraine", Id: "ua_vat",},
    {Index: 65,Text: "United Arab Emirates", Id: "ae_trn",},
    {Index: 66,Text: "United Kingdom", Id: "gb_vat",},
    {Index: 67,Text: "United Kingdom", Id: "eu_vat",},
    {Index: 68,Text: "United States", Id: "us_ein",}]    

export default {taxData, taxOptions}